import { Inter } from "next/font/google";
import { BiSolidCameraMovie } from "react-icons/bi";
import Header from "./header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MovieApi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden bg-black m-0`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
